#!/bin/bash
# shellcheck disable=1111,1112,2030,2031,2034,2086

# change if your bible folder has a different name
bible_name="bible"

main() {
  get_text $1
  get_terminal_width
  print_title "$@"
  format_markdown

  # justify text
  if [ $width -le 20 ]; then
    passes=26
  elif [ $width -le 30 ]; then
    passes=15
  elif [ $width -le 40 ]; then
    passes=8
  elif [ $width -le 50 ] || [ $width -le 60 ]; then
    passes=7
  elif [ $width -le 70 ]; then
    passes=6
  elif [ $width -le 80 ]; then
    passes=5
  else
    passes=4
  fi

  for i in $(seq 1 $passes); do
    justify_poetry
  done
  for i in $(seq 1 $passes); do
    justify_normal
  done

  cleanup
  # output
  if [[ $3 != '' ]]; then
    print_passage "$@"
  elif [[ $2 != '' ]]; then
    print_verse "$@"
  else
    print_chapter
  fi
}

set_books_array() {
  books_array='{
    "Genesis": ["gen", "gn", "ge"],
    "Exodus": ["ex", "exod", "exo"],
    "Leviticus": ["lev", "le", "lv"],
    "Numbers": ["num", "nu", "nm", "nb"],
    "Deuteronomy": ["deut", "de", "dt"],
    "Joshua": ["josh", "jos", "jsh"],
    "Judges": ["judg", "jdg", "jg", "jdgs"],
    "Ruth": ["rth", "ru"],
    "1 Samuel": ["1sam", "1sm", "1sa", "1s", "isam", "isa", "1samuel", "1sam", "1s", "1stsamuel", "1stsam", "firstsamuel", "firstsam"],
    "2 Samuel": ["2sam", "2sm", "2sa", "2s", "iizam", "iisa", "2sam", "2sam", "2s", "2ndsamuel", "2ndsam", "secondsamuel", "secondsam"],
    "1 Kings": ["1kgs", "1ki", "1kgs", "1kin", "1ki", "1k", "iikgs", "iiki", "1stkings", "1stkgs", "firstkings", "firstkgs"],
    "2 Kings": ["2kgs", "2ki", "2kgs", "2ki", "2k", "iikgs", "2ndkings", "2ndkgs", "secondkings", "secondkgs"],
    "1 Chronicles": ["1chron", "1chr", "1ch", "1chron", "1chr", "1ch", "ichron", "ichr"],
    "2 Chronicles": ["2chron", "2chr", "2ch", "2chron", "2chr", "2ch", "iichron", "iichr"],
    "Ezra": ["ezr", "ez"],
    "Nehemiah": ["neh", "ne"],
    "Esther": ["est", "esth", "es"],
    "Job": ["jb"],
    "Psalm": ["ps", "psalms", "pslm", "psa", "psm", "pss"],
    "Proverbs": ["prov", "pro", "prv", "pr"],
    "Ecclesiastes": ["eccles", "eccle", "ecc", "ec", "qoh"],
    "Song": ["songofsolomon", "songofsongs", "sos", "so", "canticleofcanticles", "canticles", "cant"],
    "Isaiah": ["isa", "is"],
    "Jeremiah": ["jer", "je", "jr"],
    "Lamentations": ["lam", "la"],
    "Ezekiel": ["ezek", "eze", "ezk"],
    "Daniel": ["dan", "da", "dn"],
    "Hosea": ["hos", "ho"],
    "Joel": ["jl"],
    "Amos": ["am"],
    "Obadiah": ["obad", "ob"],
    "Jonah": ["jnh", "jon"],
    "Micah": ["mic", "mc"],
    "Nahum": ["nah", "na"],
    "Habakkuk": ["hab", "hb"],
    "Zephaniah": ["zeph", "zep", "zp"],
    "Haggai": ["hag", "hg"],
    "Zechariah": ["zech", "zec", "zc"],
    "Malachi": ["mal", "ml"],
    "Matthew": ["matt", "mt"],
    "Mark": ["mrk", "mar", "mk", "mr"],
    "Luke": ["luk", "lk"],
    "John": ["joh", "jhn", "jn"],
    "Acts": ["act", "ac"],
    "Romans": ["rom", "ro", "rm"],
    "1 Corinthians": ["1cor", "1co", "icor", "ico", "1cor", "1co", "1corinthians", "1stcorinthians", "firstcorinthians"],
    "2 Corinthians": ["2cor", "2co", "iicor", "iico", "2cor", "2co", "2corinthians", "2ndcorinthians", "secondcorinthians"],
    "Galatians": ["gal", "ga"],
    "Ephesians": ["eph", "ephes"],
    "Philippians": ["phil", "php", "pp"],
    "Colossians": ["col", "co"],
    "1 Thessalonians": ["1thess", "1thes", "1th", "ithessalonians", "ithess", "ithes", "1thessalonians", "1thess", "1stthessalonians"],
    "2 Thessalonians": ["2thess", "2thes", "2th", "iithessalonians", "iithess", "iithes", "2thessalonians", "2thess", "2ndthessalonians"],
    "1 Timothy": ["1tim", "1ti", "itimothy", "itim", "iti", "1timothy", "1tim", "1sttimothy", "1sttim", "firsttimothy", "firsttim"],
    "2 Timothy": ["2tim", "2ti", "iitimothy", "iitim", "iiti", "2timothy", "2tim", "2ndtimothy", "2ndtim", "secondtimothy"],
    "Titus": ["tit", "ti"],
    "Philemon": ["philem", "phm", "pm"],
    "Hebrews": ["heb"],
    "James": ["jas", "jm"],
    "1 Peter": ["1pet", "1pe", "1pt", "1p", "ipet", "ipt", "ipe", "1pet", "1pt", "1p", "1peter"],
    "2 Peter": ["2pet", "2pe", "2pt", "2p", "iipet", "iipt", "iipe", "2peter", "2pt", "2peter"],
    "1 John": ["1joh", "1jhn", "1jn", "1j", "1john", "1jhn", "1joh", "1jn", "1jo", "1j", "ijohn"],
    "2 John": ["2joh", "2jhn", "2jn", "2j", "2john", "2jhn", "2joh", "2jn", "2jo", "2j", "iijohn"],
    "3 John": ["3joh", "3jhn", "3jn", "3j", "3john", "3jhn", "3joh", "3jn", "3jo", "3j", "iiijohn"],
    "Jude": ["jud", "jd"],
    "Revelation": ["rev", "re"]
  }'
}

show_help() {
  echo "Usage: $0 [-ch]"
  echo "   -c    Disable context verses"
  echo "   -h    Display help"
  echo "   -a    Display list of abbreviations"
  exit 1
}

show_abbreviations() {
  set_books_array
  get_terminal_width

  hline=$(
    printf '=%.0s' $(seq 1 "$width")
    echo
  )

  abbreviations="$(
    echo "$books_array" | jq -r 'to_entries | .[] | "\(.key) | \(.value | join(", "))"' | column -t -s '|'
  )"

  sed_args=(
    -e 's/([^ ])    ([^ ])/\1  \2/g'
    -e 's/([^ ])     ([^ ])/\1   \2/g'
    -e 's/([^ ])      ([^ ])/\1    \2/g'
    -e 's/([^ ])       ([^ ])/\1     \2/g'
    -e 's/([^ ])        ([^ ])/\1      \2/g'
    -e 's/([^ ])         ([^ ])/\1       \2/g'
    -e 's/([^ ])          ([^ ])/\1        \2/g'
    -e 's/([^ ])           ([^ ])/\1         \2/g'
    -e 's/([^ ])            ([^ ])/\1          \2/g'
    -e 's/([^ ])             ([^ ])/\1           \2/g'
    -e 's/([^ ])              ([^ ])/\1            \2/g'
    -e 's/([^ ])               ([^ ])/\1             \2/g'
    -e 's/([^ ])                ([^ ])/\1              \2/g'
    -e 's/([^ ])                 ([^ ])/\1               \2/g'
    -e 's/([^ ])                  ([^ ])/\1                \2/g'
    -e 's/^/  /g'

    # move char to newline if width-1 is a space or symbol
    -e "s/^(.{$((width - 1))})([A-Za-z0-9]*,)/\1\n                   \2/"
    -e "s/^(.{$((width))})([A-Za-z0-9]*,)/\1\n                   \2/"

    -e "s/^(.{$((width - 1))})([A-Za-z0-9]*)$/\1\n                   \2/"
    -e "s/^(.{$((width))})([A-Za-z0-9]*)$/\1\n                   \2/"
  )
  
    abbreviations=$(echo "$abbreviations" | sed -E "${sed_args[@]}")

  output="$(
    echo "$hline"
    title="Abbreviations"
    padding=$(((width + ${#title}) / 2))
    printf "%*s\n" $padding "$title"
    echo "$hline"
    echo -e "${abbreviations}"
  )"

  echo "$output" | less -RFX
  exit 1
}

find_chapter() {
  set_books_array

  # remove the trailing digits to get the book name
  book=$(echo "$1" | sed 's/[0-9]*$//')

  # remove the letters to get the chapter number
  chapter=$(echo "$1" | sed 's/^[0-9]*[a-zA-Z]*//')

  # find book in books array
  # book=$(echo "$books_array" | jq -r --arg book "$book" 'to_entries[] | select(.value[] == $book) | .key | ascii_downcase')
  book=$(echo "$books_array" | jq -r --arg book "$book" 'to_entries[] | select(.value[] | ascii_downcase == ($book | ascii_downcase)) | .key | gsub("^[ \t]+|[ \t]+$"; "") | ascii_downcase')

}
get_terminal_width() {
  width=$(tput cols)
}

get_text() {
    # find file relative to bib
  dir_of_script=$(dirname "$(readlink -f $0)")
  bible_dir="${dir_of_script}/${bible_name}"
  chapter_file="${bible_dir}/${1}.md"
  # enter if given book name is an abbreviation
  if [ ! -f "${chapter_file}" ]; then
    find_chapter $1
    chapter_file="${bible_dir}/${book}${chapter}.md"
    # enter if book name does not exist
    if [ ! -f "${chapter_file}" ]; then
      echo "[bib] chapter not found: ${1}"
      exit 1
    fi
  fi
  text=$(cat "${chapter_file}")
}

print_title() {
  hline=$(
    printf '=%.0s' $(seq 1 "$width")
    echo
  )
  if [[ $3 != '' ]]; then
    title="$(echo "$text" | grep '^# .*' | sed 's/# \(.*\) *(*[A-Z]*)*$/\1/'):$2-$3"
  elif [[ $2 != '' ]]; then
    title="$(echo "$text" | grep '^# .*' | sed 's/# \(.*\) *(*[A-Z]*)*$/\1/'):$2"
  else
    title="$(echo "$text" | grep '^# .*' | sed 's/# \(.*\) *(*[A-Z]*)*$/\1/')"
  fi
}

format_markdown() {
  sed_args=(
    # remove headings
    -e 's/^(# |#### |##### ).*//'

    # fix instances of `] [`
    -e 's/\] \[/ /'

    # format verses
    -e 's/###### (¶* *[0-9][0-9][0-9])/\1   tempnewline/g'
    -e 's/###### (¶* *[0-9][0-9])/\1    tempnewline/g'
    -e 's/###### (¶* *[0-9])/\1     tempnewline/g'
  )
  text=$(echo "$text" | sed -E "${sed_args[@]}")

  text=$(echo "$text" | sed -E ':a;$!{N;s/tempnewline\n//;ba;}')
  text=$(echo "$text" | sed -E ':a;$!{N;s/\n¶ / ~\n/;ba;}')

  sed_args=(
    # fix/remove markdown syntax
    -e 's/\\\*/tempasterisk/g'
    -e 's/==//g'
    -e 's/—/––/g'


    # italic -> brackets
    -e 's/\*([A-Za-z0-9])/[\1/g'
    -e 's/([A-Za-z0-9!?.,”’;:])\*/\1]/g'

    # \[ -> [ and \] -> ]
    -e 's/\\\[/[/g'
    -e 's/\\\]/]/g'
    -e 's/\\//g'

    # remove footnotes
    # convert footnotes
    -e 's/\[\^1\]:*/¹/g'
    -e 's/\[\^2\]:*/²/g'
    -e 's/\[\^3\]:*/³/g'
    -e 's/\[\^4\]:*/⁴/g'
    -e 's/\[\^5\]:*/⁵/g'
    -e 's/\[\^6\]:*/⁶/g'

    -e 's/^> /      > /g'
    -e 's/tempasterisk/*/g'

    # add space before lines that are not on the same line as the verse num
    -e 's/(^[^0-9 ])/      \1/g'
  )
  text=$(echo "$text" | sed -E "${sed_args[@]}")
}

justify_poetry() {
  sed_args=(
    # add newline when width is a space
    -e "s/^(.{6}>.{$((width - 9))}) /\1\n      > /"

    # hyphenate words that are in width
    -e "s/^(.{6}>.{$((width - 9))})([A-Za-z0-9])([A-Za-z0-9])([A-Za-z0-9])/\1\2-\n      > \3\4/"

    # move char to newline if width-2 is [[
    -e "s/^(.{6}>.{$((width - 10))})\[\[([A-Za-z0-9])/\1\n      > [[\2/"

    # move char to newline if width-3 is a 2-letter word with ] at end
    -e "s/^(.{6}>.{$((width - 11))}) ([A-Za-z0-9]{2}\])/\1\n      > \2/"

      # move char to newline if width-1 is a space or symbol
    -e "s/^(.{6}>.{$((width - 9))})([ “‘[({])([A-Za-z0-9“‘[({][^ ])/\1\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 9))}) ([A-Za-z0-9“‘[({][^ ])/\1\n      > \2/"

    # ] or ) not followed by space

    # move char to newline if width is a 3+ letter word + ) or ] + punctuation
    -e "s/^(.{6}>.{$((width - 11))}[A-Za-z0-9])([A-Za-z0-9]{2}\))([^ ])/\1-\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 11))}[A-Za-z0-9])([A-Za-z0-9]{2}\])([^ ])/\1-\n      > \2\3/"

    -e "s/^(.{6}>.{$((width - 10))}[A-Za-z0-9])([A-Za-z0-9]{2}\))([^ ])/\1-\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 10))}[A-Za-z0-9])([A-Za-z0-9]{2}\])([^ ])/\1-\n      > \2\3/"

    # move char to newline if width is 2 letter word + ) or ] + punctuation
    -e "s/^(.{6}>.{$((width - 11))}) ([A-Za-z0-9]{2}\))([^ ])/\1\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 10))}) ([A-Za-z0-9]{2}\))([^ ])/\1\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 11))}[A-Za-z0-9])([A-Za-z0-9]{2}\))([^ ])/\1-\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 11))}[A-Za-z0-9])([A-Za-z0-9]{2}\))([^ ])/\1-\n      > \2\3/"

    -e "s/^(.{6}>.{$((width - 11))})(\([A-Za-z0-9]{2}\))([^ ])/\1\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 10))})(\([A-Za-z0-9]{2}\))([^ ])/\1\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 11))})(\[[A-Za-z0-9]{2}\])([^ ])/\1\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 10))})(\[[A-Za-z0-9]{2}\])([^ ])/\1\n      > \2\3/"

    -e "s/^(.{6}>.{$((width - 11))}) ([A-Za-z0-9]{2}\])([^ ])/\1\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 10))}) ([A-Za-z0-9]{2}\])([^ ])/\1\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 11))}[A-Za-z0-9])([A-Za-z0-9]{2}\])([^ ])/\1-\n      > \2\3/"
    -e "s/^(.{6}>.{$((width - 10))}[A-Za-z0-9])([A-Za-z0-9]{2}\])([^ ])/\1-\n      > \2\3/"

    # ] or ) followed by space

    # move char to newline if width is a 3+ letter word + ) or ] + punctuation
    -e "s/^(.{6}>.{$((width - 10))}[A-Za-z0-9])([A-Za-z0-9]{2}\))/\1-\n      > \2/"
    -e "s/^(.{6}>.{$((width - 10))}[A-Za-z0-9])([A-Za-z0-9]{2}\])/\1-\n      > \2/"

    -e "s/^(.{6}>.{$((width - 9))}[A-Za-z0-9])([A-Za-z0-9]{2}\))/\1-\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}[A-Za-z0-9])([A-Za-z0-9]{2}\])/\1-\n      > \2/"

    # move char to newline if width is 2 letter word + ) or ] + punctuation
    -e "s/^(.{6}>.{$((width - 10))}) ([A-Za-z0-9]{2}\))/\1\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}) ([A-Za-z0-9]{2}\))/\1\n      > \2/"
    -e "s/^(.{6}>.{$((width - 10))}[A-Za-z0-9])([A-Za-z0-9]{2}\))/\1-\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}[A-Za-z0-9])([A-Za-z0-9]{2}\))/\1-\n      > \2/"

    -e "s/^(.{6}>.{$((width - 10))}) ([A-Za-z0-9]{2}\])/\1\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}) ([A-Za-z0-9]{2}\])/\1\n      > \2/"
    -e "s/^(.{6}>.{$((width - 10))}[A-Za-z0-9])([A-Za-z0-9]{2}\])/\1-\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}[A-Za-z0-9])([A-Za-z0-9]{2}\])/\1-\n      > \2/"

    # move char to newline if width + 1 is punctuation

    -e "s/^(.{6}>.{$((width - 10))}[A-Za-z0-9])([A-Za-z0-9]{2}[!?.,”’;:])/\1-\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}[A-Za-z0-9])([A-Za-z0-9]{2}[!?.,”’;:])/\1-\n      > \2/"

    -e "s/^(.{6}>.{$((width - 10))}) ([A-Za-z0-9]{2}[!?.,”’;:])/\1\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}) ([A-Za-z0-9]{2}[!?.,”’;:])/\1\n      > \2/"

    -e "s/^(.{6}>.{$((width - 10))}) ([A-Za-z0-9]{2}[!?.,”’;:])/\1\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}) ([A-Za-z0-9]{2}[!?.,”’;:])/\1\n      > \2/"

    # move char to newline if width-1 is a hyphen
    -e "s/^(.{6}>.{$((width - 9))})-([A-Za-z0-9“‘])/\1-\n      > \2/"

    # move char to newline if width-1 is an em dash
    -e "s/^(.{6}>.{$((width - 10))})––([A-Za-z0-9“‘])/\1––\n      > \2/"

    # move char to newline if width is a hyphen
    -e "s/^(.{6}>.{$((width - 9))})([A-Za-z])-([A-Za-z])/\1\2-\n      > \3/"

    # move char to newline if width is an em dash
    -e "s/^(.{6}>.{$((width - 10))})([A-Za-z])––([A-Za-z])/\1\2––\n      > \3/"

    # add newline right after punctuation
    -e "s/^(.{6}>.{$((width - 8))})([!?.,”’;:])/\1\2\n      > /"

    # fix verses that didn't get move to newline
    -e "s/^(.{6}>.{$((width - 7))}) /\1\n      > /"
    -e "s/^(.{6}>.{$((width - 7))})([!?.,”’;:])/\1\n      > \2/"
    -e "s/^(.{6}>.{$((width - 8))}) /\1\n      > /"
    -e "s/> *>/>/"

    # move char if width + 1 is punctuation
    -e "s/^(.{6}>.{$((width - 10))}) ([A-Za-z0-9]{2}[,])/\1\n      > \2/"
    -e "s/^(.{6}>.{$((width - 9))}) ([A-Za-z0-9]{2}[,])/\1\n      > \2/"

    # fix verse number spacing
    -e 's/([0-9]{1})      /\1     /g'
    -e 's/([0-9]{2})     /\1    /g'
    -e 's/([0-9]{3})    /\1   /g'

    # add newline if width+1 is a space
    -e "s/^(.{4}>.{$((width - 5))}) /\1\n      > /"
  )
  text=$(echo "$text" | sed -E "${sed_args[@]}")
}

justify_normal() {
  sed_args=(
    # add newline when width is a space
    -e "s/^(.{$((width - 1))}) /\1\n      /"

    # hyphenate words that are in width
    -e "s/^(.{$((width - 2))}[A-Za-z0-9])([A-Za-z0-9][A-Za-z0-9])/\1-\n      \2/"

    # move char to newline if width-2 is [[
    -e "s/^(.{$((width - 3))})\[\[([A-Za-z0-9])/\1\n      [[\2/"

    # move char to newline if width-3 is a 2-letter word with ] at end
    -e "s/^(.{$((width - 4))}) ([A-Za-z0-9]{2}\])/\1\n      \2/"

    # move char to newline if width-1 is a space or symbol
    -e "s/^(.{$((width - 2))})([“‘[({])([A-Za-z0-9“‘[({][^ ])/\1\n      \2\3/"
    -e "s/^(.{$((width - 2))}) ([A-Za-z0-9“‘[({][^ ])/\1\n      \2/"

    # ] or ) not followed by space

    # move char to newline if width is a 3+ letter word + ) or ] + punctuation
    -e "s/^(.{$((width - 4))}[A-Za-z0-9])([A-Za-z0-9]{2}\))([^ ])/\1-\n      \2\3/"
    -e "s/^(.{$((width - 4))}[A-Za-z0-9])([A-Za-z0-9]{2}\])([^ ])/\1-\n      \2\3/"

    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}\))([^ ])/\1-\n      \2\3/"
    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}\])([^ ])/\1-\n      \2\3/"

    # move char to newline if width is 2 letter word + ) or ] + punctuation
    -e "s/^(.{$((width - 4))}) ([A-Za-z0-9]{2}\))([^ ])/\1\n      \2\3/"
    -e "s/^(.{$((width - 3))}) ([A-Za-z0-9]{2}\))([^ ])/\1\n      \2\3/"
    -e "s/^(.{$((width - 4))}[A-Za-z0-9])([A-Za-z0-9]{2}\))([^ ])/\1-\n      \2\3/"
    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}\))([^ ])/\1-\n      \2\3/"

    -e "s/^(.{$((width - 4))})(\([A-Za-z0-9]{2}\))([^ ])/\1\n      \2\3/"
    -e "s/^(.{$((width - 3))})(\([A-Za-z0-9]{2}\))([^ ])/\1\n      \2\3/"
    -e "s/^(.{$((width - 4))})(\[[A-Za-z0-9]{2}\])([^ ])/\1\n      \2\3/"
    -e "s/^(.{$((width - 3))})(\[[A-Za-z0-9]{2}\])([^ ])/\1\n      \2\3/"

    -e "s/^(.{$((width - 4))}) ([A-Za-z0-9]{2}\])([^ ])/\1\n      \2\3/"
    -e "s/^(.{$((width - 3))}) ([A-Za-z0-9]{2}\])([^ ])/\1\n      \2\3/"
    -e "s/^(.{$((width - 4))}[A-Za-z0-9])([A-Za-z0-9]{2}\])([^ ])/\1-\n      \2\3/"
    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}\])([^ ])/\1-\n      \2\3/"

    # ] or ) followed by space

    # move char to newline if width is a 3+ letter word + ) or ] + punctuation
    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}\))/\1-\n      \2/"
    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}\])/\1-\n      \2/"

    -e "s/^(.{$((width - 2))}[A-Za-z0-9])([A-Za-z0-9]{2}\))/\1-\n      \2/"
    -e "s/^(.{$((width - 2))}[A-Za-z0-9])([A-Za-z0-9]{2}\])/\1-\n      \2/"

    # move char to newline if width is 2 letter word + ) or ] + punctuation
    -e "s/^(.{$((width - 3))}) ([A-Za-z0-9]{2}\))/\1\n      \2/"
    -e "s/^(.{$((width - 2))}) ([A-Za-z0-9]{2}\))/\1\n      \2/"
    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}\))/\1-\n      \2/"
    -e "s/^(.{$((width - 2))}[A-Za-z0-9])([A-Za-z0-9]{2}\))/\1-\n      \2/"

    -e "s/^(.{$((width - 3))}) ([A-Za-z0-9]{2}\])/\1\n      \2/"
    -e "s/^(.{$((width - 2))}) ([A-Za-z0-9]{2}\])/\1\n      \2/"
    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}\])/\1-\n      \2/"
    -e "s/^(.{$((width - 2))}[A-Za-z0-9])([A-Za-z0-9]{2}\])/\1-\n      \2/"

    # move char to newline if width + 1 is punctutation

    -e "s/^(.{$((width - 3))}[A-Za-z0-9])([A-Za-z0-9]{2}[!?.,”’;:])/\1-\n      \2/"
    -e "s/^(.{$((width - 2))}[A-Za-z0-9])([A-Za-z0-9]{2}[!?.,”’;:])/\1-\n      \2/"

    -e "s/^(.{$((width - 3))}) ([A-Za-z0-9]{2}[!?.,”’;:])/\1\n      \2/"
    -e "s/^(.{$((width - 2))}) ([A-Za-z0-9]{2}[!?.,”’;:])/\1\n      \2/"

    -e "s/^(.{$((width - 3))}) ([A-Za-z0-9]{2}[!?.,”’;:])/\1\n      \2/"
    -e "s/^(.{$((width - 2))}) ([A-Za-z0-9]{2}[!?.,”’;:])/\1\n      \2/"

    # move char to newline if width-1 is a hyphen
    -e "s/^(.{$((width - 2))})-([A-Za-z0-9“‘])/\1-\n      \2/"

    # move char to newline if width-1 is an em dash
    -e "s/^(.{$((width - 3))})––([A-Za-z0-9“‘])/\1––\n      \2/"

    # move char to newline if width is a hyphen
    -e "s/^(.{$((width - 2))})([A-Za-z])-([A-Za-z])/\1\2-\n      \3/"

    # move char to newline if width is an em dash
    -e "s/^(.{$((width - 3))})([A-Za-z])––([A-Za-z])/\1\2––\n      \3/"
    -e "s/^(.{$((width - 2))})([A-Za-z])––([A-Za-z])/\1\2––\n      \3/"

    # add newline right after punctuation
    -e "s/^(.{$((width - 1))})([!?.,”’;:])/\1\2\n      /"

    # fix verses that didn't get move to newline
    -e "s/^(.{$((width))})([!?.,”’;:])/\1\n      \2/"
    # -e "s/^(.{$((width - 1))}) /\1\n      /"

    # fix verse number spacing
    -e 's/([0-9]{1})      /\1     /g'
    -e 's/([0-9]{2})     /\1   /g'
    -e 's/([0-9]{3})   /\1  /g'
  )
  text=$(echo "$text" | sed -E "${sed_args[@]}")

  # add newline if width+1 is a space
  text=$(echo "$text" | sed -E "s/^(.{$((width))}) /\1\n      /")
}

cleanup() {
  sed_args=(
    # fix spacing
    -e 's/^ {2,4}([^ ])/      \1/g'
    -e 's/^ {6,}([^ ])/      \1/g'

    # remove unnecessary character
    -e "s/^(.{$((width - 1))})––/\1–/g"

    # change ~ back to pilcrow signs
    -e 's/~/¶/g'
  )
  text=$(echo "$text" | sed -E "${sed_args[@]}")

  text=$(echo "$text" | sed -E ':a;$!{N;s/\n *¶ */ ¶/;ba;}')
  text=$(echo "$text" | sed -E "s/^(.{$((width))})¶/\1\n     ¶/g")
  text=$(echo "$text" | sed -E ':a;$!{N;s/ ¶\n([0-9])    /\n\1   ↓/;ba;}')
  text=$(echo "$text" | sed -E ':a;$!{N;s/ ¶\n([0-9][0-9])   /\n\1  ↓/;ba;}')
  text=$(echo "$text" | sed -E ':a;$!{N;s/ ¶\n([0-9][0-9][0-9])  /\n\1 ↓/;ba;}')

  sed_args=(
    # remove blank lines
    -e 's/ *$//g'
    -e '/^$/d'
    -e '/^ *>* *$/d'

    # reformat verse nums to be right-aligned
    -e 's/^([0-9]{2}) / \1/g'
    -e 's/^([0-9]{1})  /  \1/g'
    -e 's/^([¹²³⁴⁵⁶]) (.*)/   \1[\2]/g'

    # fix verses in hundreds
    -e 's/^([0-9]{3}) *> /\1   > /g'

    # fix ↓ with no space before >
    -e "s/↓>/↓ >/"
  )
  text=$(echo "$text" | sed -E "${sed_args[@]}")
}

print_passage() {
  output="$(
    sed_args=(
      # format editorial headings
      -e 's/^ *## (.*)//'
      -e '/^$/d'
    )
    text=$(echo "$text" | sed -E "${sed_args[@]}")
    echo "$hline"
    padding=$(((width + ${#title}) / 2))
    printf "%*s\n" $padding "$title"
    echo "$hline"
    # echo -e "${text}" | awk "/^ *$(($2)) /{print; flag=1; next} /^ *$(($3 + 1)) /{flag=0} flag"
    echo -e "${text}" | awk "/^ *$(($2)) /{print \"\033[31m\" \$0; flag=1; next} /^ *$(($3 + 1)) /{flag=0} flag {print \"\033[31m\" \$0}"
  )"
  echo "$output" | less -RFX
  echo -en "\033[0m"
}

print_verse() {
    sed_args=(
      # format editorial headings
      -e 's/^ *## (.*)//'
      -e '/^$/d'
    )
  text=$(echo "$text" | sed -E "${sed_args[@]}")
  echo "$hline"
  padding=$(((width + ${#title}) / 2))
  printf "%*s\n" $padding "$title"
  echo "$hline"
  if [[ $ARG_CONTEXT == 'true' ]]; then
    echo -e "${text}" | awk "/^ *$(($2 - 2)) /{print; flag=1; next} /^ *$(($2 - 1)) /{flag=0} flag"
    echo -e "${text}" | awk "/^ *$(($2 - 1)) /{print; flag=1; next} /^ *$(($2 - 0)) /{flag=0} flag"
    echo -e "${text}" | awk "/^ *$2 /{print \"\033[31m\" \$0; flag=1; next} /^ *($(($2 + 1)) |¹)/{flag=0} flag"
    echo -en "\033[0m"
    echo -e "${text}" | awk "/^ *$(($2 + 1)) /{print; flag=1; next} /^ *($(($2 + 2)) |¹)/{flag=0} flag"
    echo -e "${text}" | awk "/^ *$(($2 + 2)) /{print; flag=1; next} /^ *($(($2 + 3)) |¹)/{flag=0} flag"
  elif [[ $ARG_CONTEXT == 'false' ]]; then
    echo -e "${text}" | awk "/^ *$2 /{print \"\033[31m\" \$0; flag=1; next} /^ *($(($2 + 1)) |¹)/{flag=0} flag"
    echo -en "\033[0m"
  fi
}

print_chapter() {
  sed_args=(
    -e '1s/^      ## (.*)/      [\1]/g'
    -e 's/^      ## (.*)/\n      [\1]/g'
    # add blank line before footnotes
    -e 's/^ *¹/\n&/'
  )
  text=$(echo "$text" | sed -E "${sed_args[@]}")
  output="$(
    echo "$hline"
    padding=$(((width + ${#title}) / 2))
    printf "%*s\n" $padding "$title"
    echo "$hline"
    echo -e "$text"
  )"
  echo "$output" | less -RFX
}

# Process command line args
ARG_CONTEXT="true"
while getopts ':cah?' c; do
  case $c in
  c) ARG_CONTEXT="false" ;;
  a) show_abbreviations ;;
  h | ?) show_help ;;
  esac
done
shift $((OPTIND - 1))

main "$@"
