#!/bin/bash
# shellcheck disable=2035

sed_args=(
  # remove certain markdown elements
  -e '/aliases/d'
  -e '/^#####.*/d'
  -e '/^---/d'
  
  # remove div tags
  -e 's/<div.*>(.*)<\/div>/\1/g'
  
  # change verses to H6
  -e 's/^<span class=verse-first>([0-9]*)<\/span>*/###### ¶ \1\n/g'
  -e 's/^<span class=verse-body>([0-9]*)<\/span>*/###### \1\n/g'
  -e 's/^><span class=verse-first-poetry>([0-9]*)<\/span>*/###### ¶ \1\n>/g'
  -e 's/^><span class=verse-body-poetry>([0-9]*)<\/span>*/###### \1\n>/g'
  
  # change HTML italics to markdown italics
  -e 's/<i>/*/g'
  -e 's/<\/i>/*/g'
  
  # remove tags surrounding quotes
  # and remove paragraph breaks
  -e 's/<span class=poetry-quote-single>//g'
  -e 's/<span class=poetry-quote-double>//g'
  -e 's/<span class=paragraph-break>//g'
  # remove lingering closing span tags
  -e 's/<\/span>//g'

  # replace small cap words
  -e 's/Lᴏʀᴅ/LORD/g'
  -e 's/Yᴀʜ/YAH/g'
  -e 's/Gᴏᴅ/GOD/g'
  -e 's/Jᴇꜱᴜꜱ/JESUS/g'
  -e 's/Cʜʀɪꜱᴛ/CHRIST/g'
)

sed -i -E "${sed_args[@]}" *.md

# remove empty lines
sed -i -E ":a;$!{N;s/\n\n/\n/;ba;}" *.md